### ISSUE TITLE
API Gateway recommended for K8s

### ISSUE THREAD

**Issue by ginoec2** [dgonzalez/ama#2]
Hola David,

            Could you please recommend an API Gateway for K8s? I heard about Ambassador (k8s native), have you worked with it? What we are trying to do is put a layer acting as a gateway/proxy redirecting internet requests to our microservices deployed on GCP and other paas like AWS/Azure.

           Thanks in advance,

Gino

**Comment by dgonzalez** [comment]
better late than never: I use nginx as ingress controller and that gives me just about the bits I need from an API Gateway.

If you need more juice, I would seriously recommend you [Kong](https://konghq.com/kong/).

**Comment by dgonzalez** [comment]
Sorry for the delay! I completely missed this.
